name: Deploy container on render.com

on: 
  workflow_dispatch:
  push:
    branches: [main]

env:
  DOCKERHUB_TAG: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest

jobs:
  mail_wrong_branch:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send alert mail
        uses: dawidd6/action-send-mail@v17
        with:
          server_address: ${{ vars.MAIL_SERVER }}
          server_port: 465
          secure: true
          username: ${{ vars.MAIL_USER }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Tu té tronc près 🚨
          to: ${{ vars.MAIL_VICTIME }}
          from: ${{ vars.MAIL_USER }}
          body: <h1>Boum !</h1>
      - name: Kill deploy
        run: |
          echo "Deploiement d'une branche non autorisé !"
          exit 1
  #TODO Ajouter un job pour lancer les tests (quand il y en aura)
  build_container:
    needs: mail_wrong_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Récuperation du code de repo git
        uses: actions/checkout@v6
      - name: Login to DockerHub # Connection à DockerHub avec le token
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push # Construction du image en envoi sur dockerhub
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.ref == 'refs/heads/main' }} # Ok si branch main
          tags: ${{ env.DOCKERHUB_TAG }}
  auto_deploy:
    needs: build_container
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy # Lancer la mise à jours sur render.com
        run: curl ${{ secrets.RENDER_TRIGGER_URL }}
